### ISSUE TITLE
CZ4034 2015-2015 Semester 2 Question 3a

### ISSUE THREAD

**Issue by Andyccs** [Andyccs/ntucs-pyp#2]
> k-means can be used for supervised learning too. I will use both clustering algo, and evaluate using the measures such as precision, recall and f-measure. Should probably use the classifier with a high f1-measure. 

@kklw Can you explain in details how k-means clustering can be used to supervised learning? or can you give any references to this? 

And since you mentioned `use both clustering algo`, do you think that kNN is a clustering algorithm?

**Comment by kklw** [comment]
Sorry, I made a mistake for this. Agree that knn is more suitable for classification. 

My impression was i read that kmeans can be used for classification too, but they are modified k-means. E.g.  [Adapting k-means for supervised](http://link.springer.com/article/10.1007%2Fs10489-006-8513-8)

> this paper demonstrates how the popular k-means clustering algorithm can be profitably modified to be used as a classifier algorithm.

**Comment by Andyccs** [comment]
@kklw Can I remove your `todo` in the answer?

**Comment by kklw** [comment]
@Andyccs Ok. No problem.

**Comment by Andyccs** [comment]
Fix 3f2d19bebaeddebe97d923229558b8108a44da9e
